<?php

//[STAMP] 5b427b1b54b359fb6893b1cc0866f238
// phpcs:ignoreFile

namespace Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();


}
